language: objective-c

branches:
 only:
 - master

xcode_project: DCPod.xcodeproj
xcode_scheme: DCPodTests
osx_image: xcode8.3

script:
- xcodebuild -scheme DCPod -project DCPod.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:
- bash <(curl -s https://codecov.io/bash)
